#+TODO: TODO IN-PROGRESS | DONE
Задания для самостоятельного выполнения:

* IN-PROGRESS Задание первое

Разработайте программу решения задачи поиска максимального значения среди минимальных элементов строк матрицы (такая задача имеет место для решения матричных игр).

* TODO Задание второе

Разработать программу для умножения матриц.

Для следующих заданий должно быть измерено следующее:
1. Время работы в последовательном режиме;
2. Время работы в параллельном режиме для различных случаев;

* TODO Задание третье

Реализовать программу, выполняющую умножение матрицы на вектор следующими способами:

• разделением данных по строкам;
• разделением данных по столбцам;
• блочным разделением данных.

Провести сравнение времени выполнения последовательной программы относительно указанных вариантов параллельной программы на различном количестве нитей (коэффициент ускорения). Размер исходных данных переменный. Результаты измерений представить в виде таблицы или графика.

* TODO Задание четвёртое

Модернизировать четвёртое задание таким образом, чтобы выполнялось умножение матриц:
• применяя ленточное разделение данных;
• применяя блочное разделение данных.

Провести сравнение времени выполнения последовательной программы относительно указанных вариантов параллельной программы на различном количестве нитей (коэффициент ускорения). Размер исходных данных переменный. Результаты измерений представить в виде таблицы или графика.

* TODO Задание пятое

Поиск шаблона в файле. Программа по поиску подстроки в строке с использованием параллельных директив.
